Solves for small "bugs"
astrojuanlu/cookiecutter-pylib pull request #2
Opened 2020-05-26 10:10 UTC by jorgepiloto

As explained in #1, this pull requests will add the following corrections:

- [x] Explicit typing so `tox mypy` testing session does not complain.
- [x] A `test_package_version` so `tox -e check` does not fail because of `imported but unused`. 
- [x] A `gitkeep` inside a `docs/source/_static` directory so `tox -e docs` not raises an error.

2020-05-27 13:23 UTC, astrojuanlu requested changes
Hi @jorgepiloto, thanks for this PR!

I'm happy with adding the fixes to `docs/`, however I don't like the test very much. I prefer that it's "broken by default" - that will force users of the template to, well, write some real tests :yum: Can we revert that part?

2020-05-27 16:47 UTC, jorgepiloto commented
Sure! Let me modify this as suggested :rocket:

2020-05-28 09:35 UTC, astrojuanlu approved these changes

2020-05-28 09:35 UTC, astrojuanlu commented
Merging this, thanks @jorgepiloto!

2020-05-28 09:35 UTC, merged